name: Build design document
run-name: ${{ github.actor }} building the Phlex design document 🚀

on:
  push:
    paths:
      - 'doc/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  Build-Design-Document-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setting up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          miniforge-version: latest
          auto-update-conda: true
          activate-environment: build_docs
          show-channel-urls: true
          conda-remove-defaults: true
          environment-file: environment.yml

      - name: Cache date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key: miniforge-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: 1
        id: cache

      - name: Build document
        working-directory: ./doc
        run: |
          conda activate build_docs
          dot -c  # because it's weird out of the box
          make html latexpdf

      - run: echo "Build status ${{ job.status }}"
