name: Build design document
run-name: ${{ github.actor }} building the Phlex design document 🚀

on:
  push:
    paths:
      - 'doc/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-design-document-action:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/framework-r-d/phlexdoc:2025-05-01

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build document
        working-directory: ./doc
        run: |
          dot -c  # because it's weird out of the box
          make html latexpdf

      - run: echo "Build status ${{ job.status }}"
