name: Build design document
run-name: ${{ github.actor }} building the Phlex design document 🚀

on:
  push:
    paths:
      - 'doc/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  Build-Design-Document-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setting up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          miniforge-version: latest
          auto-update-conda: true
          activate-environment: build_docs
          show-channel-urls: true
          conda-remove-defaults: true
          environment-file: environment.yml

      - name: Build document
        working-directory: ./doc
        run: |
          dot -c  # because it's weird out of the box
          make html latexpdf

      - run: echo "Build status ${{ job.status }}"
