name: Build design document
run-name: ${{ github.actor }} building the Phlex design document 🚀

on:
  push:
    paths:
      - 'doc/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  Build-Design-Document-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          #cache: "pip"

      - name: Install sphinx-build tool
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Build document
        working-directory: ./doc
        run: |
          . .venv/bin/activate
          make html latexpdf

      - run: echo "Build status ${{ job.status }}"
